version: "3"

services:
  app:
    container_name: mlflow
    build:
      dockerfile: Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - ./db:/mlflow/db
